### ISSUE TITLE
Consider using rust-everywhere?

### ISSUE THREAD

**Issue by dashed** [esphen/wsta#3]
https://github.com/japaric/rust-everywhere

Would you be open to using something like `rust-everywhere` to provide distributables for various platforms?

**Comment by eliihen** [comment]
I am definitely not opposed to it. Thanks for the link, I'll have a look into it!

**Comment by eliihen** [comment]
Check it out, I re-tagged the latest release, and now the binaries are rolling in: https://github.com/esphen/wsta/releases/tag/0.2.1

`rust-everywhere` is pretty cool. You just tag and push, and it spins up some travis CI workers which automatically release to GitHub when they finish compiling and testing.

Some issues, however:
1. I could not get `arm` releases  to work. This is because `libssl-dev` is not in the main repository, and no matter what witchcraft I used, I could not get amd64 trusty Ubuntu to install it from ports.
2. I was not able to statically link `openssl`, so there is potential for issues if you don't have the same version that the binary was compiled with (which at first glance looks like `1.0.1f`). This is not a new issue, however.
3. I didn't even touch windows. **That** monster will have to be tamed later.

Since I have been bashing my head against the table for some while, I figured it is better to release something now than nothing ever. It's not perfect, but it's at least more binaries than before.

Thanks again for the tip!
